export interface Opportunity {
  id: string;
  title: string;
  description: string;
  applicantsCount: number;
  average_rating: number;
  categories: string[];
  createdAt: string;
  createdBy: string;
  datePosted: string;
  deadline: string;
  endDate: string;
  engagementType: string;
  idealCandidate: string;
  isBookmarked: boolean;
  isPaid: boolean;
  isRolling: boolean;
  location: string[];
  logoUrl: string;
  opType: string;
  orgEmail: string;
  orgID: string;
  orgName: string;
  orgPrimaryPhone: string;
  paymentOption: {
    currency: string;
    paymentType: string;
  };
  perksAndBenefits: string[] | null;
  questions: string[] | null;
  requiredSkills: string[];
  requirements: string;
  responsibilities: string;
  startDate: string;
  status: string;
  total_reviews: number;
  updatedAt: string;
  viewsCount: number;
  whenAndWhere: string;
}
